pom.xml, ramls/notify.json, src/main/java/org/folio/rest/impl/NotificationsResourceImpl.java, src/main/resources/template_create_tenant.sql
Still has to be snapshot, until the real one gets released
=> Use RMB 14.0.0

src/main/java/org/folio/rest/impl/NotificationsResourceImpl.java
Bit of refactoring, lot of merging lines
=> Last desperate tricks to increase test coverage

pom.xml, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/NotifyTest.java
Had to define the ginIndex, only for the text of the notify,
and change a lookup in the tests to use proper wildcards on the link.
=> Using rmb16

ramls/notify.json, ramls/notify.raml
=> MODNOTIFY-24 fix raml title

src/test/java/org/folio/rest/impl/SendNotifyTest.java
=> Wait for postTenant to complete in setUp MODNOTIFY-45

src/test/java/org/folio/rest/impl/SendNotifyTest.java
Stop embedded postgres after tests completed.
=> MODNOTIFY-45: Stop embedded postgres

ramls/event_entity.json, ramls/event_entity_collection.json, ramls/message.json, ramls/notify.json, ramls/notify.raml, src/main/java/org/folio/helper/NotificationsHelper.java, src/main/java/org/folio/rest/impl/NotificationsResourceImpl.java, src/test/java/org/folio/rest/impl/SendNotifyTest.java
MODNOTIFY-41 Updating contracts to get event config by human-readable name
=> MODNOTIFY-41 Updating contracts

pom.xml
=> [MODNOTIFY-65] Update RMB to v29.3.1

README.md, ramls/notify.raml, ramls/patron-notice.raml
Resolves MODNOTIFY-61.
RAMLs are updated to include entity schemas and samples for patron-notice endpoint, readme file is also updated.
=> MODNOTIFY-61 Update ramls and readme

pom.xml, src/main/java/org/folio/helper/OkapiModulesClientHelper.java, src/main/java/org/folio/rest/impl/NotificationsResourceImpl.java, src/main/java/org/folio/rest/impl/PatronNoticeResourceImpl.java, src/test/java/org/folio/rest/impl/NotificationsResourceImplTest.java, src/test/java/org/folio/rest/impl/PatronNoticeResourceImplTest.java
Resolves MODNOTIFY-62.
Purpose: cover API classes with unit tests.
=> MODNOTIFY-62 Create unit tests

pom.xml, src/main/java/org/folio/rest/impl/NotificationsResourceImpl.java, src/main/java/org/folio/rest/impl/PatronNoticeResourceImpl.java, src/test/java/org/folio/rest/impl/NotificationsResourceImplTest.java, src/test/java/org/folio/rest/impl/NotifyTest.java
- Update to RMB v30.0.1
- Update vertx to 3.9.1
- Do all related changes according to RMB upgrading notes
Resolves: [MODNOTIFY-75](https://issues.folio.org/browse/MODNOTIFY-75)
=> MODNOTIFY-75 update RMB and vertx versions

pom.xml
Resolves [MODNOTIFY-83](https://issues.folio.org/browse/MODNOTIFY-83)
=> MODNOTIFY-83 Upgrade to RMB 31.1.5

descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/rest/impl/NotificationsResourceImpl.java, src/main/java/org/folio/rest/impl/PatronNoticeResourceImpl.java, src/test/java/org/folio/rest/impl/NotificationsResourceImplTest.java, src/test/java/org/folio/rest/impl/NotifyTest.java, src/test/java/org/folio/rest/impl/SendNotifyTest.java
Resolves: [MODNOTIFY-85](https://issues.folio.org/browse/MODNOTIFY-85)
=> MODNOTIFY-85 Upgrade to RMB v32

NEWS.md, pom.xml
Resolves [MODNOTIFY-89](https://issues.folio.org/browse/MODNOTIFY-89).
=> [MODNOTIFY-89] Release 2.9.0

pom.xml, src/test/java/org/folio/helper/WebClientFactoryTest.java
[MODNOTIFY-104](https://issues.folio.org/browse/MODNOTIFY-104)
_RMB v34 upgrade_
=> MODNOTIFY-104: RMB v34 upgrade

pom.xml
[MODNOTIFY-111](https://issues.folio.org/browse/MODNOTIFY-111)
=> [MODNOTIFY-111] Upgrade to RMB 35.0.0 and Vertx 4.3.3

NEWS.md, pom.xml
https://issues.folio.org/browse/MODNOTIFY-115
=> MODNOTIFY-115: Release 2.12.0

PULL_REQUEST_TEMPLATE.md, src/main/resources/log4j2-json.properties, src/main/resources/log4j2.properties
https://issues.folio.org/browse/MODNOTIFY-119
=> MODNOTIFY-119: Logging improvement - check log4j configuration

src/main/java/org/folio/client/NoticesClient.java, src/main/java/org/folio/client/OkapiClient.java
MODNOTIFY-125 (https://issues.folio.org/browse/MODNOTIFY-125)
Investigate the Email body generated in logs while sending Notices.
Fixed Logs that reveal complete email body.
=> MOD-NOTIFY-125 Investigate the Email body generated in logs while sending Notices.

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
=> MODNOTIFY-130 - Poppy Release

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
=> Release 3.2.0

descriptors/ModuleDescriptor-template.json
Change the permission name and bump up the message-delivery interface version.
=> MODNOTIFY-135 - Change the permission name 

descriptors/ModuleDescriptor-template.json, pom.xml
To fix the permissions as per MODAUD-134
Split the permission that were used by 2 APIs
Related PR's 
https://github.com/folio-org/mod-users-bl/pull/194
https://github.com/folio-org/folio-integration-tests/pull/1564
https://github.com/folio-org/mod-users-keycloak/pull/107
=> MODNOTIFY-134 - Changes made in MD file for permissions.

.github/workflows/postgres.yml, pom.xml, src/test/java/org/folio/rest/impl/PatronNoticeTest.java
=> MODNOTIFY-136 - Upgrade RMB version to 35.3.0

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
https://folio-org.atlassian.net/browse/MODNOTIFY-138
=> MODNOTIFY-138: Ramsons release

.github/workflows/postgres.yml, Dockerfile, Jenkinsfile, pom.xml
=> FOLIO-4226 - Java and RMB version upgrade.

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/client/OkapiClient.java
[MODNOTIFY-143](https://folio-org.atlassian.net/browse/MODNOTIFY-143)
=> MODNOTIFY-143 Sunflower R1 2025 
